# Fundamentals of arrays in Julia
### Dr. Tirthajyoti Sarkar, Fremont, CA

- [Basic array creation](#Basic-array-creation)
- [Size and dimension](#Size-and-dimension)

## Basic array creation

In [1]:
# Creating an empty array
my_array = []

0-element Array{Any,1}

In [2]:
# Creating an empty array with an abstract type
my_array = (Integer)[]

0-element Array{Integer,1}

In [3]:
# Creating an empty array with a concrete type (results in fastest operation)
my_array = (Float64)[]

0-element Array{Float64,1}

In [4]:
# Array with three elements (here the type will be inferred automatically by Julia)
array1 = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

This would be akin to what we would consider a column vector in mathematics.  We couls also create a row vector by omitting the commas.

In [5]:
array2 = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

We could transpose `array1`, which would make it similar to array `array2`.  Remember that a transpose action interchanges rows and columns.

In [6]:
# Syntax one
transpose(array1)

1×3 LinearAlgebra.Transpose{Int64,Array{Int64,1}}:
 1  2  3

In [7]:
# Syntax 2
array1'

1×3 LinearAlgebra.Adjoint{Int64,Array{Int64,1}}:
 1  2  3

In [8]:
# Is the transpose equal to the row array
array1' == array2

true

But the type of the transposed array is not exactly same. We can use the `===` strict equality operator to test that

In [9]:
typeof(array1')

LinearAlgebra.Adjoint{Int64,Array{Int64,1}}

In [10]:
array1'===array2

false

We used integers as element values.  Arrays will take on the type of the element that is *more encompassing*.  In the example below, two values will be of `Int64` type, but the last is of `Float64` type.  The array will return the `Float64` type.

In [11]:
array3 = [1, 2, 3.0]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

We can create arrays with more than just a single row or column of elements.  This would be akin to a mathematical matrix.  We can even create multidimensional arrays.  We achieve this by nesting our square brackets and playing with commas and semicolons.

In [12]:
# Note the omission of commas between the inner nested square brackets
array4 = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [13]:
# If we want to populate the elements along row first, we use semicolons
array5 = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

[Back to the top of this section](#Basic-array-creation)

## Size and dimension

In [14]:
# Checking how many elements we have
length(array5)

9

In [15]:
# Checking size or dimension
size(array4)

(3, 3)

In [16]:
# The number of dimension
a = rand(3,2,2);
println(ndims(a))

3


[Back to the top of this section](#Size-and-dimension)

## Creating and reshaping

Repeating values is easily accomplished with the `repmat([arrayvalues], number of repititions)` functions.

In [17]:
# Repeating the values 1 and 2 along a column
repeat([1, 2], 3)

6-element Array{Int64,1}:
 1
 2
 1
 2
 1
 2

In [18]:
# ...or each value as a row
repeat([1 2],3)

3×2 Array{Int64,2}:
 1  2
 1  2
 1  2

We can use built-in functions to create arrays. These can be used in other ways as we will see later.

The `range(start value, end value, number of steps)` can be used as an array.

In [19]:
# The values 0 to 10
range(0, 10, length=11)

0.0:1.0:10.0

To access the actuale values, we use the `collect()` function.

In [20]:
array6 = collect(range(0, 10, length=11))

11-element Array{Float64,1}:
  0.0
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

To create a logarithmic range i.e. to create a $10^i$ to $10^𝑓$ collection of 20 values...

In [21]:
# i = 2 and f = 3, Note the space between 10 and .^
array7 = collect(10 .^(range(2, 3, length=20)))

20-element Array{Float64,1}:
  100.0             
  112.88378916846895
  127.42749857031335
  143.8449888287663 
  162.37767391887226
  183.29807108324357
  206.913808111479  
  233.57214690901213
  263.6650898730358 
  297.63514416313194
  335.9818286283781 
  379.26901907322497
  428.13323987193957
  483.2930238571752 
  545.559478116852  
  615.8482110660261 
  695.1927961775605 
  784.7599703514614 
  885.8667904100823 
 1000.0             

In [22]:
array7 = collect(0:1:5)

6-element Array{Int64,1}:
 0
 1
 2
 3
 4
 5

In [23]:
array8 = collect(0:2:5)

3-element Array{Int64,1}:
 0
 2
 4

In [24]:
# Creating an empty array of two rows and three columns
# Using an abstract type to leave the values empty
array9 = Array{Integer}(undef, 2,3)

2×3 Array{Integer,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [25]:
# Specifying a concrete (numerical) type will add random value
array10 = Array{Int64}(undef,3, 3)

3×3 Array{Int64,2}:
 311417264  311417360  311419888
 311417296  311419216  311417488
 311419280  311419952  311417520

Lastly in this section we will take a look at reshaping an array.  Given an array of elements, we can simply change its dimensions.

In [26]:
# Remember array7
array7

6-element Array{Int64,1}:
 0
 1
 2
 3
 4
 5

In [62]:
# Reshaping it into an array with 2 rows and 3 columns
reshape(array7, 2, 3)

2×3 Array{Int64,2}:
 0  2  4
 1  3  5

In [63]:
# Reshaping it into an array with 3 rows and 2 columns
reshape(array7, 3, 2)

3×2 Array{Int64,2}:
 0  3
 1  4
 2  5

[Back to the top of this section](#Creating-and-reshaping)

## Slicing

When arrays get to larger and larger size, we may want to select only sections of it, based on some rule or rules. In this section we recap some of the ways in which this can be achieved and add some new ones.

The `rand()` function returns a random value between 0 and 1. We can also specify values to select from. In the example below we choose integers in the range \[10, 20] and create an array with ten rows and five columns.

In [29]:
array11 = rand(10:20, 10, 5)

10×5 Array{Int64,2}:
 11  15  14  16  18
 11  18  10  16  10
 15  15  18  16  12
 16  15  14  11  12
 20  20  19  15  13
 16  11  17  15  18
 15  14  11  14  14
 11  12  18  14  17
 17  11  15  11  18
 10  13  13  16  13

In [30]:
# Selecting all row values in column 2
array11[:, 2]

10-element Array{Int64,1}:
 15
 18
 15
 15
 20
 11
 14
 12
 11
 13

In [31]:
# All row values in columns 2 and 5
array11[:, [2, 5]]

10×2 Array{Int64,2}:
 15  18
 18  10
 15  12
 15  12
 20  13
 11  18
 14  14
 12  17
 11  18
 13  13

In [32]:
# All row values in columns 2, 3, and 4
array11[:, 2:4]

10×3 Array{Int64,2}:
 15  14  16
 18  10  16
 15  18  16
 15  14  11
 20  19  15
 11  17  15
 14  11  14
 12  18  14
 11  15  11
 13  13  16

In [33]:
# Values in rows 2, 4, 6, and in columns 1 and 5
array11[[2, 4, 6], [1, 5]]

3×2 Array{Int64,2}:
 11  10
 16  12
 16  18

In [34]:
# Values in row 1 from column 3 to the last column
array11[1, 3:end]

3-element Array{Int64,1}:
 14
 16
 18

[Back to the top of this section](#Slicing)

## Logic on arrays
Now we take a look at applying some rules. Note how we use the element-wise logic operator in the form of the dot (note the `.>` operator in the code below). 

Furthermore, by using the `findall()` function we can return the index values.

In [35]:
# Boolean logic (returning only true and false)
array11[:, 1] .> 12

10-element BitArray{1}:
 0
 0
 1
 1
 1
 1
 1
 0
 1
 0

In [36]:
# Returning the index of true values using findall()
findall(array11[:, 1] .> 12)

6-element Array{Int64,1}:
 3
 4
 5
 6
 7
 9

[Back to the top of this section](#Logic-on-arrays)

## Modification
Collections of elements in the form of arrays can be made much more useful if we could alter the actual values. 

We'll start off by adding elemnts to the end of an existing array. This can be done with the `push()!` function. Later, we will add a value at the start of an array using the `unshift!()` function.

In [37]:
array12 = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [38]:
# Adding the value 5 at the end of the array
push!(array12, 5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [39]:
# Adding the value 0 at the start of the array
unshift!(array12, 0)

UndefVarError: UndefVarError: unshift! not defined

[Back to the top of this section](#Modification)

## Array comprehension

In [40]:
# Create an array with elements 3.x^2 where x is an odd number between 1 and 9 (inclusive)
array13 = [3*i^2 for i in 1:2:9]

5-element Array{Int64,1}:
   3
  27
  75
 147
 243

In [41]:
# Can use multiple variables for the initialization of 2D array
array14 = [a+2b for a in -1:1, b in -2:2]

3×5 Array{Int64,2}:
 -5  -3  -1  1  3
 -4  -2   0  2  4
 -3  -1   1  3  5

In [42]:
# Array of squared elements if the square is not divisible by 5 or 4 (note that we need to use &&)
array15=[i^2 for i=1:10  if (i^2%5!=0 && i^2%4!=0)]

4-element Array{Int64,1}:
  1
  9
 49
 81

[Back to the top of this section](#Array-comprehension)

## Simple summary operations
- `sum`
- `prod`
- `mean`
- `std`
- `middle`
- `median`

In [43]:
array15

4-element Array{Int64,1}:
  1
  9
 49
 81

In [44]:
sum(array15)

140

In [45]:
prod(array15)

35721

Functions like `mean()`, `std()` and `middle()` have been moved into the `Statistics` module in the standard library; you may need to first enter `"using Statistics"` to use them

In [46]:
using Statistics

In [47]:
mean(array15)

35.0

In [48]:
std(array15)

37.16629297271027

In [49]:
middle(array15)

41.0

In [50]:
median(array15)

29.0

For 2D arrays, we can specify dimensions (axis) along which the summary operation is to be performed

In [51]:
array14

3×5 Array{Int64,2}:
 -5  -3  -1  1  3
 -4  -2   0  2  4
 -3  -1   1  3  5

In [52]:
std(array14)

3.0472470011002204

In [53]:
mean(array14,dims=1)

1×5 Array{Float64,2}:
 -4.0  -2.0  0.0  2.0  4.0

In [54]:
mean(array14,dims=2)

3×1 Array{Float64,2}:
 -1.0
  0.0
  1.0

[Back to the top of this section](#Simple-summary-operations)

## Element-wise operations

In [55]:
array16 = [2*a+b for a in 1:3, b in -2:2]

3×5 Array{Int64,2}:
 0  1  2  3  4
 2  3  4  5  6
 4  5  6  7  8

In [56]:
array14

3×5 Array{Int64,2}:
 -5  -3  -1  1  3
 -4  -2   0  2  4
 -3  -1   1  3  5

In [57]:
array14+array16

3×5 Array{Int64,2}:
 -5  -2  1   4   7
 -2   1  4   7  10
  1   4  7  10  13

In [58]:
# Note the DOT in fron of the * to denote element-wise operation
array14.*array16

3×5 Array{Int64,2}:
   0  -3  -2   3  12
  -8  -6   0  10  24
 -12  -5   6  21  40

In [59]:
array14./array16

3×5 Array{Float64,2}:
 -Inf     -3.0       -0.5       0.333333  0.75    
   -2.0   -0.666667   0.0       0.4       0.666667
   -0.75  -0.2        0.166667  0.428571  0.625   

We can even raise one array to the power of another array element-wise. But for this to work, at least one of them has to be a `Float` type, not `Integer`. So, we create a `Float64` array and demonstrate this.

In [60]:
array17 = (Float64)[a+b for a in 1:3, b in -1:3]

3×5 Array{Float64,2}:
 0.0  1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0  5.0
 2.0  3.0  4.0  5.0  6.0

In [61]:
array16.^array17

3×5 Array{Float64,2}:
  1.0    1.0     4.0     27.0     256.0
  2.0    9.0    64.0    625.0    7776.0
 16.0  125.0  1296.0  16807.0  262144.0