# Linear algebra with Julia
### Dr. Tirthajyoti Sarkar, Fremont, CA

- [Sum (of the elements)](#Sum-(of-the-elements))
- [Product (of the elements)](#Product-(of-the-elements))
- [Mean](#Mean)
- [Transpose, diagonal, trace](#Transpose,-diagonal,-trace)
- [Rank, determinant, inverse, nullspace](#Rank,-determinant,-inverse,-nullspace)
- [Vector and matrix norms](#Vector-and-matrix-norms)
- [Scaling, rotating, and reversing](#Scaling,-rotating,-and-reversing)
- [Matrix multiplication, identity, dot product](#Matrix-multiplication,-identity,-dot-product)

In [1]:
# Creating a 4x3 array with random integeres (between 1 and 20)
a = reshape(rand(1:20,12),4,3)

4×3 Array{Int64,2}:
  7   5   1
  6  15  15
  7   9   9
 12  13  11

## Sum (of the elements)

In [2]:
sum(a)

110

In [3]:
sum(a,dims=1)

1×3 Array{Int64,2}:
 32  42  36

In [4]:
sum(a,dims=2)

4×1 Array{Int64,2}:
 13
 36
 25
 36

## Product (of the elements)

In [5]:
prod(a)

45972927000

In [6]:
prod(a,dims=1)

1×3 Array{Int64,2}:
 3528  8775  1485

In [7]:
prod(a,dims=2)

4×1 Array{Int64,2}:
   35
 1350
  567
 1716

## Mean

In [8]:
using Statistics

In [9]:
mean(a)

9.166666666666666

In [10]:
mean(a,dims=1)

1×3 Array{Float64,2}:
 8.0  10.5  9.0

In [11]:
mean(a,dims=2)

4×1 Array{Float64,2}:
  4.333333333333333
 12.0              
  8.333333333333332
 12.0              

## Transpose, diagonal, trace

You need to use the `LinearAlgebra` library for most of the functions here on. Also, we need a square matrix for most of these functions, so we create one...

In [12]:
using LinearAlgebra

In [13]:
b = reshape(rand(1:20,16),4,4)

4×4 Array{Int64,2}:
 19  19  19   3
  9   7  18   6
 17  13   4   1
 13  19   8  12

In [14]:
transpose(b)

4×4 Transpose{Int64,Array{Int64,2}}:
 19   9  17  13
 19   7  13  19
 19  18   4   8
  3   6   1  12

In [15]:
# Trace of the matrix i.e. sum of the diagonal elements
tr(b)

42

In [16]:
# Extract the diagonal elements as an array
diag(b)

4-element Array{Int64,1}:
 19
  7
  4
 12

## Rank, determinant, inverse, nullspace

In [17]:
# Rank
rank(b)

4

In [18]:
# Inverse
inv(b)

4×4 Array{Float64,2}:
 -0.107135    0.093385    0.154173   -0.0327564
  0.136653   -0.138936   -0.1134      0.0447547
  0.0435337   0.0299427  -0.0477808  -0.021873 
 -0.129327    0.0988533   0.0443831   0.0625398

In [19]:
# Determinant
det(b)

18835.999999999993

For non-square matrices like `a`, there is no strict inverse but of course there is a [pseudo-inverse function](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse) `pinv` for those...

In [20]:
# Pseudo-inverse
pinv(a)

3×4 Array{Float64,2}:
 -0.0670103  -0.168587   0.124621   0.134021
  0.338488    0.264099  -0.261472  -0.176976
 -0.310997   -0.130079   0.213362   0.121993

To properly show a nullspace, we need a matrix which is not [full-rank](https://www.cds.caltech.edu/~murray/amwiki/index.php/FAQ:_What_does_it_mean_for_a_non-square_matrix_to_be_full_rank%3F) i.e. we need to have linearly dependent rows/columns. So, we create one from the matrix `a` 

In [21]:
c = [a 2*a[:,2]]

4×4 Array{Int64,2}:
  7   5   1  10
  6  15  15  30
  7   9   9  18
 12  13  11  26

In [22]:
# Rank of c matrix is less than its dimension
rank(c)

3

In [23]:
nullspace(c)

4×1 Array{Float64,2}:
  0.0                  
 -0.8944271909999157   
 -5.273559366969494e-16
  0.4472135954999582   

## Vector and matrix norms
The [Euclidean norm](https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm), ${‖\bf{X}‖}_{2} = \sqrt{x_1^2 + x_2^2 + \ldots + x_n^2}$ is found by `LinearAlgebra.norm(x)`. Arguments can be passed on to calculate other norms too...

In [24]:
X = [2, 4, -5]

3-element Array{Int64,1}:
  2
  4
 -5

In [25]:
# Euclidian norm
norm(X)

6.708203932499369

In [26]:
# L1 norm (the sum of element magnitudes i.e. absolute values)
norm(X,1)

11.0

There is, of course, the notion of [_infinity norm_](https://en.wikipedia.org/wiki/Norm_(mathematics)#Maximum_norm_(special_case_of:_infinity_norm,_uniform_norm,_or_supremum_norm)) $||\bf{X}||_\infty$, which is basically equivalent to the max value of the vector/matrix. We cannot go up to true infinity of course, but if we take a sufficiently large norm say 20, we will see that the value is pretty close to the max element of the `X` i.e. 5. And then we can use `Inf` as the argument.

In [27]:
norm(X,20)

5.002866639190858

In [28]:
norm(X,Inf)

5.0

The Euclidian distance between two vectors $\bf{X}$ and $\bf{Y}$ is given by $||\bf{X}-\bf{Y}||_2$ and can be computed easily in Julia using `norm(X-Y)`...

In [29]:
X = [2, 4, -5];
Y = [1,-1,3];
norm(X-Y)

9.486832980505138

We can verify the answer using the basic definition i.e. _square-root of the sum of the difference of the elements_...

In [30]:
sqrt(sum((X-Y).^2))

9.486832980505138

The [angle between two vectors](https://onlinemschool.com/math/library/vector/angl/) $\bf{X}$ and $\bf{Y}$ is given by: 
$$\text{cos}^{-1}\frac{X^TY}{||X||_2||Y||_2}$$

In [31]:
acos((transpose(X)*Y)/(norm(X)*norm(Y)))

2.4404307889469252

For 2-D vectors i.e. matrices, we need to use the `opnorm()` function to compute the so-called [operator norm](https://en.wikipedia.org/wiki/Operator_norm). 1-norm of a matrix (the maximum absolute column sum):

In [32]:
d = [5 -4 2 ; -1 2 3; -2 1 0]

3×3 Array{Int64,2}:
  5  -4  2
 -1   2  3
 -2   1  0

In [33]:
opnorm(d,1)

8.0

... and here's the infinity norm (the maximum absolute row sum)

In [34]:
opnorm(d,Inf)

11.0

Euclidian norm is the default

In [35]:
opnorm(d)

7.147682841795258

## Scaling, rotating, and reversing

In [36]:
d

3×3 Array{Int64,2}:
  5  -4  2
 -1   2  3
 -2   1  0

In [37]:
# Note that this is a bang function and changes the original matrix in-place
rmul!(d,2)

3×3 Array{Int64,2}:
 10  -8  4
 -2   4  6
 -4   2  0

In [38]:
d = [5 -4 2 ; -1 2 3; -2 1 0];
# Rotating 180 degree
rot180(d)

3×3 Array{Int64,2}:
 0   1  -2
 3   2  -1
 2  -4   5

In [39]:
# Reversing rows
reverse(d,dims=1)

3×3 Array{Int64,2}:
 -2   1  0
 -1   2  3
  5  -4  2

In [40]:
# Reversing columns
reverse(d,dims=2)

3×3 Array{Int64,2}:
 2  -4   5
 3   2  -1
 0   1  -2

## Matrix multiplication, identity, dot product

In [41]:
A = reshape(rand(1:10,6),2,3);
B = reshape(rand(1:10,12),3,4);

In [42]:
A

2×3 Array{Int64,2}:
 8  7  5
 1  7  5

In [43]:
B

3×4 Array{Int64,2}:
 2   9  5  10
 9   1  4   8
 6  10  4   7

$\bf{A}$ is a $2\times3$ matrix and $\bf{B}$ is a $3\times4$ matrix. So, their matrix product will be a $2\times4$ matrix.

In [44]:
A*B

2×4 Array{Int64,2}:
 109  129  88  171
  95   66  53  101

Identity matrix of any dimension can be computed by `Matrix()` function and using the special `I` element

In [45]:
Matrix{Int}(I, 3, 3)

3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1

In [46]:
Matrix{Float64}(I, 3, 3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

As we know from the definition of the matrix inverse, that $\bf{A}.\bf{B}=\bf{I}$ if $\bf{B}$ is an inverse of $\bf{A}$ i.e. $\bf{B}=\bf{A}^{-1}$. We can check by creating a random matrix, computing its inverse, and then multiplying the original matrix with the inverse. Note, that we will not get an exact identity matrix because of numerical precision limit but the diagonal elements will be very close to 1 and off-diagonal elements will be very close to zero.

In [47]:
A = reshape(rand(1:10,9),3,3);
B = inv(A);
A*B

3×3 Array{Float64,2}:
  1.0          2.22045e-16  2.22045e-16
 -1.11022e-16  1.0          0.0        
 -1.11022e-16  1.11022e-16  1.0        

Dot product between two vectors is computed by the `dot()` function

In [48]:
X = [2, 4, -5];
Y = [1,-1,3];
dot(X,Y)

-17