# Data structures in Julia
### [Dr. Tirthajyoti Sarkar](https://www.linkedin.com/in/tirthajyoti-sarkar-2127aa7/), Fremont, CA ([Homepage](https://tirthajyoti.github.io))
---

### Why do we need data structures
Once we start working with many pieces of data at once, it will be convenient for us to store data in structures like arrays or dictionaries (rather than just relying on variables).<br>

Types of data structures covered in this notebook:
1. [Tuples](#Tuples)
2. [Named Tuples](#Named-Tuples)
3. [Dictionary](#Dictionary)
4. [Sets](#Sets)
5. [Arrays](#Arrays)

As an overview, tuples and arrays are both ordered sequences of elements (so we can index into them). Dictionaries and arrays are both mutable.
We'll explain these concepts more below with examples!

### Note on arrays: 
Array is probably the most useful data structure in Julia for data science and machine learning work. If you have worked with `NumPy` in Python, you will understand what that is the case. All kinds of advanced statistical and linear algebra operations can be performed on arrays in Julia right out of the box! Julia arrays, therefore, are as powerful as NumPy arrays but they are native to Julia, unlike Python, where `NumPy` library needed to be built separetly.

**This is why we will devote a complete (separate) notebook to arrays in Julia. In the current notebook, we just introduce the concept of arrays for the sake of completeness.** So, the treatment of arrays is short here.

## Tuples
We can create a tuple by enclosing an ordered collection of elements in `( )`.

In [1]:
favoritelang = ("Python","Julia","R")

("Python", "Julia", "R")

In [2]:
typeof(favoritelang)

Tuple{String,String,String}

### Indexing
We can index into this tuple,

In [3]:
println("The first favorite language is: $(favoritelang[1])")
println("...and the first two are: $(favoritelang[1:2])")

The first favorite language is: Python
...and the first two are: ("Python", "Julia")


Note that when indexing a single item, we got back a `String`, but when we indexed more than one items, we got back a `Tuple`

### Immutability
We cannot, however, mutate (i.e. change) a tuple because they are immutable variables/objects (much like Python).

In [4]:
favoritelang[1]="JavaScript"

MethodError: MethodError: no method matching setindex!(::Tuple{String,String,String}, ::String, ::Int64)

### Iteration
We can iterate over a tuple.

In [5]:
for lang in favoritelang
    print(lang);print(", ")
end

Python, Julia, R, 

### Few useful methods (general to all data structures)
- `isempty` - checks if the data structure is empty, 
- `length` - returns the length of the data structure, 
- `in` - checks for membership of an element,
- `unique` - returns a collection of unique elements,
- `reduce` - reduces the given collection `itr` with the given binary operator `op`,
- `maximum` (or `minimum`) - returns the largest (or smallest) result of calling function `fun` on each element of `itr`

In [6]:
isempty(favoritelang)

false

In [7]:
length(favoritelang)

3

In [8]:
"Java" in favoritelang

false

In [9]:
"Julia" in favoritelang

true

In [10]:
favoritelang2 = ("Python","Julia","R","Julia","Python");
println("Printing all the elements:")
for lang in favoritelang2
    print(lang);print(", ")
end
println("\n\nNow printing only the unique elements:")
for lang in unique(favoritelang2)
    print(lang);print(", ")
end

Printing all the elements:
Python, Julia, R, Julia, Python, 

Now printing only the unique elements:
Python, Julia, R, 

In [11]:
reduce(*,favoritelang)

"PythonJuliaR"

In [12]:
t = (2,3,-4);
reduce(+,t)

1

In [13]:
# Python is the longest string, so we expect the answer to be 6
maximum(length,favoritelang)

6

In [14]:
# R is the shortest string, so we expect the answer to be 1
minimum(length,favoritelang)

1

## Named Tuples

Named Tuples are available for Julia>=1.0.

As you might guess, `NamedTuple`s are just like `Tuple`s except that each element additionally has a name! They have a special syntax using `=` inside a tuple:

```julia
(name1 = item1, name2 = item2, ...)
```

In [15]:
favoritelang = (general="Python",datascience="Julia",stats="R")

(general = "Python", datascience = "Julia", stats = "R")

In [16]:
typeof(favoritelang)

NamedTuple{(:general, :datascience, :stats),Tuple{String,String,String}}

When we will discuss dictonaries (or if you are already familiar with the key-value pair concept from other languages), you can get the idea already!

In [17]:
favoritelang[2]

"Julia"

They also add the special ability to access values by their name,

In [18]:
favoritelang.general

"Python"

## Dictionary

If we have sets of data related to one another, we may choose to store that data in a dictionary. Its implementation uses [`hash`](https://docs.julialang.org/en/v1/base/base/#Base.hash) as the hashing function for the key, and [`isequal`](https://docs.julialang.org/en/v1/base/base/#Base.isequal) to determine equality. 

We can create a dictionary using the `Dict()` function, which we can initialize as an empty dictionary or one storing key, value pairs.

Syntax:

```
Dict(key1 => value1, key2 => value2, ...)
```

This call will attempt to **infer type information** from the keys and values. 
<br>To **explicitly specify types** use the syntax,
```
Dict{KeyType,ValueType}(...). 
```
For example, 
```
Dict{String,Int32}("A"=>1, "B"=>2)
```

A good example is a contacts list, where we associate names with phone numbers.

In [19]:
phonebook = Dict("Rambo" => "111-867-5309", "Ghostbusters" => "555-2368","James Bond" => "007-007-007")

Dict{String,String} with 3 entries:
  "James Bond"   => "007-007-007"
  "Rambo"        => "111-867-5309"
  "Ghostbusters" => "555-2368"

In this example, each name and number is a "key" and "value" pair. We can grab Rambo's number (a value) using the associated key,

In [20]:
phonebook["Rambo"]

"111-867-5309"

Alternatively, we can construct dictionaries from a list (array) of `(key, value)` pairs as tuples,

In [21]:
Dict([("A", 1), ("B", 2)])

Dict{String,Int64} with 2 entries:
  "B" => 2
  "A" => 1

Unlike tuples, however, dictionaries are mutable and we can easily add another entry to our `phonebook`,

In [22]:
phonebook["Seinfield"] = "123-456-7890";
phonebook

Dict{String,String} with 4 entries:
  "James Bond"   => "007-007-007"
  "Seinfield"    => "123-456-7890"
  "Rambo"        => "111-867-5309"
  "Ghostbusters" => "555-2368"

We can delete `Rambo` from our contact list - and simultaneously grab his number - by using `pop!`

In [23]:
pop!(phonebook,"Rambo")

"111-867-5309"

In [24]:
phonebook

Dict{String,String} with 3 entries:
  "James Bond"   => "007-007-007"
  "Seinfield"    => "123-456-7890"
  "Ghostbusters" => "555-2368"

Unlike tuples and arrays, dictionaries are not ordered. So, we can't index into them. 
<br>In the example below, Julia thinks you're trying to access a value associated with the key `1`.

In [25]:
phonebook[1]

KeyError: KeyError: key 1 not found

### Some useful methods
- `keys`
- `values`
- `pairs`
- `haskey`

In [26]:
keys(phonebook)

Base.KeySet for a Dict{String,String} with 3 entries. Keys:
  "James Bond"
  "Seinfield"
  "Ghostbusters"

In [27]:
values(phonebook)

Base.ValueIterator for a Dict{String,String} with 3 entries. Values:
  "007-007-007"
  "123-456-7890"
  "555-2368"

In [28]:
pairs(phonebook)

Dict{String,String} with 3 entries:
  "James Bond"   => "007-007-007"
  "Seinfield"    => "123-456-7890"
  "Ghostbusters" => "555-2368"

In [29]:
haskey(phonebook,"Kramer")

false

In [30]:
haskey(phonebook,"Seinfield")

true

### The `merge()` function
This function constructs a merged collection from the given collections. If necessary, the types of the resulting collection will be promoted to accommodate the types of the merged collections. If the same key is present in another collection, the value for that key will be the value it has in the last collection listed.

In [31]:
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);

In [32]:
a

Dict{String,Float64} with 2 entries:
  "bar" => 42.0
  "foo" => 0.0

In [33]:
b

Dict{String,Real} with 2 entries:
  "bar" => 13.0
  "baz" => 17

In [34]:
# Note the order of merging
merge(a, b)

Dict{String,Real} with 3 entries:
  "bar" => 13.0
  "baz" => 17
  "foo" => 0.0

In [35]:
# Now the order is reversed
merge(b,a)

Dict{String,Real} with 3 entries:
  "bar" => 42.0
  "baz" => 17
  "foo" => 0.0

If `merge()` is used with a `combiner` function argument, then the values with the same key will be combined using the combiner function.

In [36]:
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);

# Using a +(sum) function as the combiner
merge(+,a,b)

Dict{String,Real} with 3 entries:
  "bar" => 55.0
  "baz" => 17
  "foo" => 0.0

## Sets
Julia has native support for set-like collections much like Python's `set` object type. It provides all the basic functions of standard set algebra for operating on them.

We can construct a set using the `Set()` function from an iterable collection as argument. Note that only the unique elements will be in the resulting set and any duplicates will be discarded.

In [37]:
Set([1,2,3,1,4,5,2])

Set([4, 2, 3, 5, 1])

### Checking equality, subset/superset relationship

In [38]:
S1 = Set([1,2,3,4]);
S2 = Set([3,4]);

In [39]:
issubset(S1,S2)

false

In [40]:
issubset(S2,S1)

true

In [41]:
S1 = Set([1,2]);
S2 = Set([3,4]);

In [42]:
issetequal(S1,S2)

false

In [43]:
S1 = Set([1,2,2,3,1,2,3,2,1]);
S2 = Set([2,3,1]);

In [44]:
issetequal(S1,S2)

true

### Union

In [45]:
# Union
S1 = Set([1,2]);
S2 = Set([3,4]);
union(S1,S2)

Set([4, 2, 3, 1])

In [46]:
# Union
S1 = Set([1,2]);
S2 = Set([2,4]);
union(S1,S2)

Set([4, 2, 1])

### Intersection

In [47]:
# Intersect
S1 = Set([1,2]);
S2 = Set([2,4]);
intersect(S1,S2)

Set([2])

In [48]:
# Intersect
S1 = Set([1,2]);
S2 = Set([3,4]);
intersect(S1,S2)

Set(Int64[])

### Set difference

In [49]:
# Set difference
S1 = Set([1,2,3]);
S2 = Set([3,4,5]);
setdiff(S1,S2)

Set([2, 1])

### Symmetric difference

In [50]:
# Symmetric difference
S1 = Set([1,2,3]);
S2 = Set([3,4,5]);
symdiff(S1,S2)

Set([4, 2, 5, 1])

## Arrays

An array is a collection of objects stored in a multi-dimensional grid. **For numerical computing, data analytics, and machine learning, an array, which has been optimized for speed, can be a powerful object to utilize**. For example, almost all data science and machine learning focused libraries in Python ecosystem utilizes the core numerical data type - NumPy arrays - in some form or other, as this specialized data structure provides order-of-magnitude higher speed benefit compared to the plain vanilla Python list/array objects.

Julia, like most technical computing languages, provides a first-class array implementation. However, in general, **unlike many other technical computing languages, Julia does not expect programs to be written in a vectorized style for performance**. Julia's **compiler uses type inference and generates optimized code** for scalar array indexing, allowing programs to be written in a style that is convenient and readable, without sacrificing performance, and using less memory at times.

In [51]:
# Creating an empty array
my_array = []

0-element Array{Any,1}

In [52]:
# Creating an empty array with an abstract type
my_array = (Integer)[]

0-element Array{Integer,1}

In [53]:
# Creating an empty array with a concrete type (results in fastest operation)
my_array = (Float64)[]

0-element Array{Float64,1}

In [54]:
# Array with three elements (here the type will be inferred automatically by Julia)
array1 = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

This would be akin to what we would consider a column vector in mathematics. We couls also create a row vector by omitting the commas.

In [55]:
array2 = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

If we mix various types of elements in an array, then arrays will take on the type of the element that is *more encompassing*.  In the example below, two values will be of `Int64` type, but the last is of `Float64` type.  The array will return the `Float64` type.

In [56]:
array3 = [1, 2, 3.0]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [57]:
array4 = ["one",pi,42];
for i in array4
    println("Type of \'$i\' is $(typeof(i))")
end

Type of 'one' is String
Type of 'π' is Irrational{:π}
Type of '42' is Int64


We can create arrays with more than just a single row or column of elements. This would be akin to a mathematical matrix. We can even create multidimensional arrays. We achieve this by nesting our square brackets and playing with commas and semicolons.

In [58]:
# Note the omission of commas between the inner nested square brackets
array5 = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [59]:
# If we want to populate the elements along row first, we use semicolons
array6 = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

### Size and dimension
- `length()`
- `size()`
- `ndims()`

In [60]:
array6

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [61]:
# Checking how many elements we have
length(array6)

9

In [62]:
# Checking size or dimension
size(array6)

(3, 3)

In [63]:
# Creating a 3D array of random floats
a = rand(3,2,2);
ndims(a)

3

### Special arrays - `ones`, `zeros`, `fill`

In [64]:
ones((2,3))

2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [65]:
zeros(3,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [66]:
fill([1,2],3)

3-element Array{Array{Int64,1},1}:
 [1, 2]
 [1, 2]
 [1, 2]

### Reshaping, transposing, and slicing/indexing

In [67]:
a = collect(1:12);
a

12-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12

In [68]:
reshape(a,(2,6))

2×6 Array{Int64,2}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [69]:
reshape(a,(3,4))

3×4 Array{Int64,2}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [70]:
b = reshape(a,(3,4));
c=transpose(b)

4×3 LinearAlgebra.Transpose{Int64,Array{Int64,2}}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

Note the type of the transposed array. It is a part of a type `LinearAlgebra` now. We will talk about this type and library much more in a separate notebook.

In [71]:
# Indexing - 2nd row, 3rd column
c[2,3]

6

In [72]:
# All of the 3rd row
c[3,:]

3-element Array{Int64,1}:
 7
 8
 9

In [73]:
# All of the 2nd column
c[:,2]

4-element Array{Int64,1}:
  2
  5
  8
 11

In [74]:
# A block consisting of 2nd and 4th rows and 1st and 3rd column
c[[2,4],[1,3]]

2×2 Array{Int64,2}:
  4   6
 10  12

### Check out notebooks on arrays and linear algebra operations
Arrays support almost all kinds of statistical and linear algebra operations that you can think of. They are the bedrock of all data science and machine learning packages in Julia ecosystem. We have a separate notebook dedicated to array operations and another notebook just on the linear algebra operations.